//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public answer()
        {
            this.answer_rankings = new HashSet<answer_rankings>();
        }
    
        public int id { get; set; }
        public int question_id { get; set; }
        public string contents { get; set; }
        public int ranking { get; set; }
        public int author_id { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual ICollection<answer_rankings> answer_rankings { get; set; }
        public virtual question question { get; set; }
        public virtual user user { get; set; }
    }
}
