//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int id { get; set; }
        public int notification_type { get; set; }
        public string message { get; set; }
        public System.DateTime timestamp { get; set; }
        public int recipient { get; set; }
        public byte seen { get; set; }
    
        public virtual user user { get; set; }
    }
}
