//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public question()
        {
            this.answers = new HashSet<answer>();
            this.question_rankings = new HashSet<question_rankings>();
            this.tags = new HashSet<tag>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string contents { get; set; }
        public int ranking { get; set; }
        public int author_id { get; set; }
        public byte recommended { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<int> right_answer_id { get; set; }
    
        public virtual ICollection<answer> answers { get; set; }
        public virtual ICollection<question_rankings> question_rankings { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<tag> tags { get; set; }
    }
}
