//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.answer_rankings = new HashSet<answer_rankings>();
            this.answers = new HashSet<answer>();
            this.question_rankings = new HashSet<question_rankings>();
            this.questions = new HashSet<question>();
            this.notifications = new HashSet<notification>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public byte isadmin { get; set; }
        public byte isowner { get; set; }
        public byte ismuted { get; set; }
        public int ranking { get; set; }
        public System.DateTime created { get; set; }
        public string pwd { get; set; }
    
        public virtual ICollection<answer_rankings> answer_rankings { get; set; }
        public virtual ICollection<answer> answers { get; set; }
        public virtual ICollection<question_rankings> question_rankings { get; set; }
        public virtual ICollection<question> questions { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
    }
}
